version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    env_file:
      - .env

  worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info -Q default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"